name: "Hazelcast .NET Client Actions"
description: "Actions for the Hazelcast .NET Client"
author: "stephane.gay@hazelcast.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"